### ISSUE TITLE
Rename book to 'SecDevOps Risk Workflow'

### ISSUE THREAD

**Issue by DinisCruz** [DinisCruz/Book_SecDevOps_Risk_Workflow#17]
Following from @davevs question on [scope creep?](https://github.com/DinisCruz/Book_Jira_Risk_Workflow/issues/15) , rename book to 'SecDevOps Risk Workflow'
- [x] Rename book name in Leanpub - https://leanpub.com/secdevops
- [x] Rename GitHub repos - [main repo](https://github.com/DinisCruz/Book_SecDevOps_Risk_Workflow) ,  [build repo](https://github.com/DinisCruz/Book_SecDevOps_Risk_Workflow_Build)
- [x] Update cover
- [X] Update book intro (kinda-ish done)
- [x] Update README.md text and Image
- [X] Create new release - See [v0.57](https://github.com/DinisCruz/Book_SecDevOps_Risk_Workflow/releases/tag/v0.57)

**Comment by DinisCruz** [comment]
![image](https://cloud.githubusercontent.com/assets/656739/19413428/7610634e-9324-11e6-930a-97a0a10ffed1.png)

![image](https://cloud.githubusercontent.com/assets/656739/19413445/35dca0d4-9325-11e6-959b-21de67112875.png)

**Comment by DinisCruz** [comment]
Following from @davevs question on [scope creep?](https://github.com/DinisCruz/Book_Jira_Risk_Workflow/issues/15) , rename book to 'SecDevOps Risk Workflow'

- [x] Rename book name in Leanpub - https://leanpub.com/secdevops
- [ ] Rename GitHub repos - [Book_SecDevOps_Risk_Workflow](https://github.com/DinisCruz/Book_SecDevOps_Risk_Workflow) ,  [Book_SecDevOps_Risk_Workflow_Build](https://github.com/DinisCruz/Book_SecDevOps_Risk_Workflow_Build)
- [ ] Update cover
- [ ] Update book intro
- [ ] Update README.md text and Image

**Comment by DinisCruz** [comment]
Book cover done and book published at https://leanpub.com/secdevops

![image](https://cloud.githubusercontent.com/assets/656739/19414110/ce74ac32-933a-11e6-9634-c5d9e725866d.png)

**Comment by streichsbaer** [comment]
Hey @DinisCruz, after reading the table of contents and parts of the book, I feel that the title is not accurate and SecDevOps is not reflecting the intent well.

Some of the titles mentioned in https://github.com/DinisCruz/Book_Jira_Risk_Workflow/issues/15 are good in my opinion. I also think however that instead of Agile you could use the term Continuous. 

Something like Continuous Application Risk Management would make more sense to me. This could be further enhanced with a tag line such as - And how to foster security as part of a DevOps culture. 

To summarize, something along the lines of: 
"Continuous Application Risk Management" - And how to foster security as part of a DevOps culture. 

This would allow setting the stage by talking about the history of Agile, DevOps and how traditional security approaches are not working in environments where software is released frequently. Then introduces the concept of embedding security into an Agile + DevOps environment and what the key aspects are in terms of culture and responsibilities. Which then leads to the main topic of the book which is how application risk can be managed seamlessly in an ongoing and integrated fashion.

What do you think?

**Comment by davevs** [comment]
@streichsbaer I agree with your remarks, but I fear that 'Continuous Application Risk Management' is too generic and will lose focus....

**Comment by DinisCruz** [comment]
Hi @streichsbaer I really like the "Continuous Application Risk Management" concept and the way you described is really good

Like @davevs mentions, I think it is a bit generic and it is more of a section of this book  (I captured it here https://github.com/DinisCruz/Book_SecDevOps_Risk_Workflow/issues/79 to that it is added at some stage)

The 'SecDevOps' is a concept that once I thought about it (thx to @davevs comment) it just felt right (it also as a good amount of energy and focus at the moment)

The more I looked at DevOps and SecDevOps/DevSecOps/DevOpsSec the more I realised that there was a gap into those books on the 'Dev' part. There is a lot of 'OPeratioS and 'SECurity' concepts/ideas/tools, but not much about the 'DEVelopment' part (somehow it fells that as long as we have good CI and lots of tools running, the code with automagically be secure :)  )
